//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSicil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iletisim
    {
        public int id { get; set; }
        public string adsoyad { get; set; }
        public string eposta { get; set; }
        public string tip { get; set; }
        public string baslik { get; set; }
        public string konu { get; set; }
        public string telefon { get; set; }
    }
}
