//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSicil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Isverenler
    {
        public int id { get; set; }
        public string yetkiliadsoyad { get; set; }
        public string eposta { get; set; }
        public string sifre { get; set; }
        public string telefon { get; set; }
        public string firmadi { get; set; }
        public string adres { get; set; }
        public string firmalogo { get; set; }
        public string sehir { get; set; }
        public string siteadresi { get; set; }
        public Nullable<int> bakiye { get; set; }
        public string kadi { get; set; }
        public string goruntuleme { get; set; }
        public string kimlikonay { get; set; }
        public string dolandirici { get; set; }
        public string onay { get; set; }
        public string uyelik_tarihi { get; set; }
    }
}
