//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSicil.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineSicilDBEntities2 : DbContext
    {
        public OnlineSicilDBEntities2()
            : base("name=OnlineSicilDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<iletisim> iletisim { get; set; }
        public virtual DbSet<Isciler> Isciler { get; set; }
        public virtual DbSet<Isverenler> Isverenler { get; set; }
        public virtual DbSet<SicilKayitlari> SicilKayitlari { get; set; }
        public virtual DbSet<Yorumlar> Yorumlar { get; set; }
    }
}
