//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSicil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SicilKayitlari
    {
        public int id { get; set; }
        public string ekleyenkadi { get; set; }
        public string sicilbilgi { get; set; }
        public string adsoyad { get; set; }
        public string eposta { get; set; }
        public string telefon { get; set; }
        public string sehir { get; set; }
        public string dogumtarihi { get; set; }
        public string resim { get; set; }
        public string kanit1 { get; set; }
        public string kanit2 { get; set; }
        public string kanit3 { get; set; }
        public string kanit4 { get; set; }
        public string kanit5 { get; set; }
        public string firmaunvani { get; set; }
        public string firmaadresi { get; set; }
        public string firmasitesi { get; set; }
        public string aciklama { get; set; }
        public string goruntuleme { get; set; }
        public string kimlikonay { get; set; }
        public string dolandirici { get; set; }
        public string eklenme_tarihi { get; set; }
    }
}
