//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSicil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorumlar
    {
        public int id { get; set; }
        public Nullable<int> sicilid { get; set; }
        public string yorumyapanid { get; set; }
        public string yorum { get; set; }
        public string tarih { get; set; }
    }
}
